(executable
 (name profile_resample)
 (libraries soundml nx unix))

(executable
 (name bitdump)
 (libraries soundml nx))

(executable
 (name profile_fft)
 (libraries nx unix))

(executable
 (name profile_io)
 (libraries soundml_io nx nx.buffer unix))

(executable
 (name gate_io)
 (libraries soundml soundml_io io_bench_corpus nx unix))
