#!/bin/sh
# The C ceiling leg of the io benchmark: builds soundml-io/bench/bench_sndfile.c
# and runs every mode over the shared io corpus (generated by the OCaml bench
# on first use — run `dune exec soundml-io/bench/bench_io.exe -- --quick` once
# if the corpus directory does not exist yet).
#
# Usage: sh dev/run_io_ceiling.sh [corpus_dir] > ceiling.csv
# Output: the harness's CSV rows (mode,path,n,frames,channels,sr,min_ns,median_ns).
set -eu

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
corpus=${1:-${SOUNDML_IO_BENCH_CORPUS:-${TMPDIR:-/tmp}/soundml-io-bench-corpus-v2}}
corpus=${corpus%/}

if [ ! -f "$corpus/wav-pcm16_22050_mo_1s.wav" ]; then
  echo "corpus not found at $corpus — generate it first:" >&2
  echo "  dune exec soundml-io/bench/bench_io.exe -- --quick" >&2
  exit 2
fi

bin=$here/_bench_sndfile
cc -O2 -o "$bin" "$root/soundml-io/bench/bench_sndfile.c" \
  $(pkg-config --cflags --libs sndfile)

# reads and header probes: small (1 s mono 22050) and bulk (30 s stereo
# 44100) per family; iteration counts sized so a row is ~seconds at most
for fam in wav-pcm16 wav-pcm24 wav-pcm32 wav-float32 flac ogg; do
  case $fam in
    flac) ext=flac ;;
    ogg) ext=ogg ;;
    *) ext=wav ;;
  esac
  "$bin" read "$corpus/${fam}_22050_mo_1s.$ext" 200
  "$bin" read_alloc "$corpus/${fam}_22050_mo_1s.$ext" 200
  "$bin" read "$corpus/${fam}_44100_st_30s.$ext" 30
  "$bin" read_alloc "$corpus/${fam}_44100_st_30s.$ext" 30
  "$bin" read "$corpus/${fam}_44100_mo_30s.$ext" 30
  "$bin" read_alloc "$corpus/${fam}_44100_mo_30s.$ext" 30
  "$bin" open "$corpus/${fam}_44100_st_30s.$ext" 300
done

# writes: the 30 s stereo float32 payload re-encoded per family
for fmt in wav16 wav24 wavf flac ogg; do
  case $fmt in
    flac) ext=flac ;;
    ogg) ext=ogg ;;
    *) ext=wav ;;
  esac
  "$bin" write "$corpus/wav-float32_44100_st_30s.wav" \
    "$corpus/_ceiling_write_tmp.$ext" "$fmt" 12
done

# the many-small-files ingest loop
for cls in wav-pcm16 wav-float32 flac; do
  "$bin" many "$corpus/many/$cls.list" 12
done

rm -f "$corpus"/_ceiling_write_tmp.* "$bin"
