(* The acceptance harness: spec assertions in decibels, never bit comparisons
   against a reference binary.

   Every row measures SoundML's own output — tone SFDR, tone THD+N, out-of-band
   rejection, passband flatness and edge, swept-sine worst alias, round-trip
   SNR, and the full standard-rate matrix — against fixed thresholds calibrated
   4-8 dB below the measured worst case of the shipped design and at-or-under
   measured soxr HQ. The SoXR oracle appears only as committed measurement data
   (test/vectors/resample/soxr_reference.json, regenerated by
   bench/soxr_reference.py): the passband-edge row asserts against its measured
   edge, and its SFDR/THD+N/sweep columns are the recorded calibration context.
   The metric definitions here mirror that script line for line, so the two
   sides always measure with the same ruler.

   Both offline surfaces are measured — [apply] (the normative executor) and
   [apply_gemm] (numerically distinct by contract) — at both dtypes where the
   metric can resolve a difference. The float32 columns sit at the float32
   arithmetic floor (about -133 dB THD+N regardless of filter length), which is
   why they are looser than the float64 ones. *)

open Windtrap
open Soundml

(* {2 The surfaces under test} *)

type surface =
  { sname: string
  ; conv: 'a. Resample.Config.t -> (float, 'a) Nx.t -> (float, 'a) Nx.t }

let surfaces =
  [ {sname= "apply"; conv= (fun c x -> Resample.apply c x)}
  ; {sname= "gemm"; conv= (fun c x -> Resample.apply_gemm c x)} ]

let c_path = List.hd surfaces

type prec = F64 | F32

let precs = [F64; F32]

let pname = function F64 -> "f64" | F32 -> "f32"

(* [convert s p cfg x] runs surface [s] at precision [p] over the float64 signal
   [x] and is the output back in float64 for analysis. *)
let convert s p cfg x =
  let n = Array.length x in
  match p with
  | F64 ->
      Nx.to_array (s.conv cfg (Nx.create Nx.float64 [|n|] x))
  | F32 ->
      Nx.to_array
        (Nx.cast Nx.float64 (s.conv cfg (Nx.create Nx.float32 [|n|] x)))

(* {2 Signals} *)

let pi = Float.pi

let tone ~sr ~f ~seconds =
  let n = Float.to_int (Float.round (Float.of_int sr *. seconds)) in
  Array.init n (fun i ->
      Float.sin (2. *. pi *. f *. Float.of_int i /. Float.of_int sr) )

let tone_set target =
  if target = 16000 then [1000.; 3000.; 6500.]
  else [1000.; 5000.; 10000.; 17000.]

(* {2 Analysis (mirrors bench/soxr_reference.py)} *)

let trim_fraction = 0.15

let fundamental_half_width = 16

let kaiser beta n = Nx.to_array (Window.make Nx.float64 (Window.Kaiser beta) n)

let largest_pow2 n =
  let p = ref 1 in
  while !p * 2 <= n do
    p := !p * 2
  done ;
  !p

(* [interior x] is the 15 %-trimmed interior of [x], cropped to a power of two
   for the FFT rows. *)
let interior x =
  let n = Array.length x in
  let i0 = Float.to_int (Float.of_int n *. trim_fraction) in
  let cut = Array.sub x i0 (n - (2 * i0)) in
  Array.sub cut 0 (largest_pow2 (Array.length cut))

let spectrum x =
  let cut = interior x in
  let n = Array.length cut in
  let w = kaiser 30. n in
  let prod = Array.init n (fun i -> w.(i) *. cut.(i)) in
  Nx.to_array
    (Nx.Complex.abs Nx.float64
       (Nx.rfft Nx.complex128 (Nx.create Nx.float64 [|n|] prod)) )

let peak_index mags =
  let best = ref 0 in
  Array.iteri (fun i m -> if m > mags.(!best) then best := i) mags ;
  !best

let sfdr mags =
  let p = peak_index mags in
  let lo = Stdlib.max 0 (p - fundamental_half_width) in
  let hi = Stdlib.min (Array.length mags) (p + fundamental_half_width + 1) in
  let spur = ref 0. in
  Array.iteri
    (fun i m ->
      if i >= 2 && (not (i >= lo && i < hi)) && m > !spur then spur := m )
    mags ;
  20. *. Float.log10 (mags.(p) /. !spur)

let thdn mags =
  let p = peak_index mags in
  let lo = Stdlib.max 0 (p - fundamental_half_width) in
  let hi = Stdlib.min (Array.length mags) (p + fundamental_half_width + 1) in
  let fund = ref 0. and rest = ref 0. in
  Array.iteri
    (fun i m ->
      let e = m *. m in
      if i >= lo && i < hi then fund := !fund +. e else rest := !rest +. e )
    mags ;
  10. *. Float.log10 (!rest /. !fund)

(* [amp_at ~sr ~f x] is the amplitude of the [f]-hertz component over the
   trimmed interior, by windowed projection at the exact frequency — no bin
   quantization, no scalloping. *)
let amp_at ~sr ~f x =
  let n = Array.length x in
  let i0 = Float.to_int (Float.of_int n *. trim_fraction) in
  let len = n - (2 * i0) in
  let w = kaiser 30. len in
  let re = ref 0. and im = ref 0. and wsum = ref 0. in
  for i = 0 to len - 1 do
    let ph = 2. *. pi *. f *. Float.of_int (i0 + i) /. Float.of_int sr in
    let v = w.(i) *. x.(i0 + i) in
    re := !re +. (v *. Float.cos ph) ;
    im := !im +. (v *. Float.sin ph) ;
    wsum := !wsum +. w.(i)
  done ;
  2. *. Float.hypot !re !im /. !wsum

let peak_dbfs x =
  let n = Array.length x in
  let i0 = Float.to_int (Float.of_int n *. trim_fraction) in
  let peak = ref 0. in
  for i = i0 to n - i0 - 1 do
    let v = Float.abs x.(i) in
    if v > !peak then peak := v
  done ;
  20. *. Float.log10 (Float.max !peak Float.min_float)

(* {2 The conversions under test} *)

let mains = [(44100, 48000); (48000, 44100); (44100, 16000)]

let cfg ?(quality = `High) (sample_rate, target) =
  Resample.Config.create ~quality ~sample_rate ~target ()

(* {2 Q1/Q2 — tone SFDR and THD+N} *)

let q1_q2 () =
  test "Q1/Q2: tone SFDR and THD+N at `High" (fun () ->
      List.iter
        (fun ((sr, target) as pair) ->
          let c = cfg pair in
          List.iter
            (fun s ->
              List.iter
                (fun p ->
                  let sfdr_min = match p with F64 -> 130. | F32 -> 125. in
                  List.iter
                    (fun f ->
                      let y = convert s p c (tone ~sr ~f ~seconds:2.) in
                      let mags = spectrum y in
                      let d = sfdr mags and t = thdn mags in
                      if d < sfdr_min then
                        failf "%d->%d %s %s %g Hz: SFDR %.1f dB < %.0f" sr
                          target s.sname (pname p) f d sfdr_min ;
                      if t > -125. then
                        failf "%d->%d %s %s %g Hz: THD+N %.1f dB > -125" sr
                          target s.sname (pname p) f t )
                    (tone_set target) )
                precs )
            surfaces )
        mains )

let q1_tiers () =
  test "Q1: tier-scaled SFDR at `Fast and `Best" (fun () ->
      List.iter
        (fun (quality, qn, sfdr_min) ->
          let c = cfg ~quality (44100, 48000) in
          List.iter
            (fun f ->
              let y = convert c_path F64 c (tone ~sr:44100 ~f ~seconds:2.) in
              let d = sfdr (spectrum y) in
              if d < sfdr_min then
                failf "44100->48000 %s %g Hz: SFDR %.1f dB < %.0f" qn f d
                  sfdr_min )
            (tone_set 48000) )
        [(`Fast, "fast", 85.); (`Best, "best", 130.)] )

(* {2 Q3 — out-of-band alias rejection (the decimation-cutoff probe)} *)

let q3 () =
  test "Q3: out-of-band tones vanish from a 16 k target" (fun () ->
      let tones = [9000.; 12000.; 18000.] in
      let run ~quality ~qn ~s ~p ~limit =
        let c = cfg ~quality (44100, 16000) in
        List.iter
          (fun f ->
            let y = convert s p c (tone ~sr:44100 ~f ~seconds:2.) in
            let peak = peak_dbfs y in
            if peak > limit then
              failf "%s %s %s %g Hz: residual peak %.1f dBFS > %.0f" qn s.sname
                (pname p) f peak limit )
          tones
      in
      List.iter
        (fun s ->
          run ~quality:`High ~qn:"high" ~s ~p:F64 ~limit:(-130.) ;
          run ~quality:`High ~qn:"high" ~s ~p:F32 ~limit:(-125.) )
        surfaces ;
      run ~quality:`Fast ~qn:"fast" ~s:c_path ~p:F64 ~limit:(-85.) ;
      run ~quality:`Best ~qn:"best" ~s:c_path ~p:F64 ~limit:(-130.) )

(* {2 Q4 — passband flatness} *)

let q4 () =
  test "Q4: passband flat to 0.913 of the lower Nyquist" (fun () ->
      List.iter
        (fun ((sr, target) as pair) ->
          let c = cfg pair in
          let edge = 0.913 *. (Float.of_int (Stdlib.min sr target) /. 2.) in
          let freqs = [100.; 0.25 *. edge; 0.5 *. edge; 0.75 *. edge; edge] in
          List.iter
            (fun s ->
              List.iter
                (fun p ->
                  let limit = match p with F64 -> 0.01 | F32 -> 0.02 in
                  List.iter
                    (fun f ->
                      let y = convert s p c (tone ~sr ~f ~seconds:1.) in
                      let dev =
                        Float.abs (20. *. Float.log10 (amp_at ~sr:target ~f y))
                      in
                      if dev > limit then
                        failf "%d->%d %s %s %g Hz: gain off by %.4f dB > %.2f"
                          sr target s.sname (pname p) f dev limit )
                    freqs )
                precs )
            surfaces )
        mains )

(* {2 Q5 — the passband edge, against the committed soxr oracle} *)

let vectors_dir = Filename.concat ".." (Filename.concat "vectors" "resample")

let oracle name =
  let file =
    Tutils.Golden.load (Filename.concat vectors_dir "soxr_reference.json")
  in
  match
    List.find_opt
      (fun c -> c.Tutils.Golden.name = name)
      file.Tutils.Golden.cases
  with
  | Some c ->
      c.Tutils.Golden.values.(0)
  | None ->
      failf "oracle case %s missing from soxr_reference.json" name

let measured_edge c ~sr ~target =
  let goal = 1. /. Float.sqrt 2. in
  let gain f =
    let y = convert c_path F64 c (tone ~sr ~f ~seconds:1.) in
    amp_at ~sr:target ~f y
  in
  let nyq = Float.of_int (Stdlib.min sr target) /. 2. in
  let lo = ref (0.85 *. nyq) and hi = ref (0.9995 *. nyq) in
  if not (gain !lo > goal && goal > gain !hi) then
    failf "edge bisection unbracketed for %d->%d" sr target ;
  for _ = 1 to 40 do
    let mid = 0.5 *. (!lo +. !hi) in
    if gain mid > goal then lo := mid else hi := mid
  done ;
  0.5 *. (!lo +. !hi)

let q5 () =
  test "Q5: -3 dB edge within 1 % of measured soxr_hq" (fun () ->
      List.iter
        (fun ((sr, target) as pair) ->
          let expected = oracle (Printf.sprintf "edge_hq_%d_%d" sr target) in
          let got = measured_edge (cfg pair) ~sr ~target in
          let dev = Float.abs (got -. expected) /. expected in
          if dev > 0.01 then
            failf "%d->%d: edge %.1f Hz vs soxr %.1f Hz (%.2f %% > 1 %%)" sr
              target got expected (100. *. dev) )
        mains )

(* {2 Q6 — swept-sine worst alias} *)

let sweep_seconds = 30.

let sweep_nfft = 8192

let sweep_hop = 4096

let sweep_worst s p ~sr ~target c =
  let nyq_out = Float.of_int target /. 2. in
  let f0 = 1000. and f1 = 0.9 *. nyq_out in
  let rate = (f1 -. f0) /. sweep_seconds in
  let n = Float.to_int (Float.of_int sr *. sweep_seconds) in
  let x =
    Array.init n (fun i ->
        let t = Float.of_int i /. Float.of_int sr in
        Float.sin (2. *. pi *. ((f0 *. t) +. (0.5 *. rate *. t *. t))) )
  in
  let y = convert s p c x in
  let w = kaiser 16. sweep_nfft in
  let guard =
    (3. *. rate *. (Float.of_int sweep_nfft /. Float.of_int target)) +. 400.
  in
  let skip = Float.to_int (0.2 *. Float.of_int target) in
  let worst = ref Float.neg_infinity in
  let start = ref skip in
  let bin_hz = Float.of_int target /. Float.of_int sweep_nfft in
  while !start + sweep_nfft <= Array.length y - skip do
    let center = !start + (sweep_nfft / 2) in
    let f_inst = f0 +. (rate *. (Float.of_int center /. Float.of_int target)) in
    let frame = Array.init sweep_nfft (fun i -> w.(i) *. y.(!start + i)) in
    let mags =
      Nx.to_array
        (Nx.Complex.abs Nx.float64
           (Nx.rfft Nx.complex128 (Nx.create Nx.float64 [|sweep_nfft|] frame)) )
    in
    let peak = ref 0. and alias = ref 0. in
    Array.iteri
      (fun i m ->
        if i >= 3 then
          if Float.abs ((Float.of_int i *. bin_hz) -. f_inst) <= guard then (
            if m > !peak then peak := m )
          else if m > !alias then alias := m )
      mags ;
    let r = 20. *. Float.log10 (!alias /. !peak) in
    if r > !worst then worst := r ;
    start := !start + sweep_hop
  done ;
  !worst

let q6 () =
  test "Q6: sweep worst alias at `High" (fun () ->
      List.iter
        (fun ((sr, target) as pair) ->
          let c = cfg pair in
          List.iter
            (fun s ->
              List.iter
                (fun p ->
                  let worst = sweep_worst s p ~sr ~target c in
                  if worst > -100. then
                    failf "%d->%d %s %s: worst alias %.1f dB > -100" sr target
                      s.sname (pname p) worst )
                precs )
            surfaces )
        mains )

let q6_tiers () =
  test "Q6: tier-scaled sweep at `Fast and `Best" (fun () ->
      List.iter
        (fun (quality, qn, limit) ->
          let c = cfg ~quality (44100, 48000) in
          let worst = sweep_worst c_path F64 ~sr:44100 ~target:48000 c in
          if worst > limit then
            failf "44100->48000 %s: worst alias %.1f dB > %.0f" qn worst limit )
        [(`Fast, "fast", -85.); (`Best, "best", -100.)] )

(* {2 The FFT-executed classes, held to the same thresholds}

   The `High plans of record run 8 <-> 48 kHz through the interpolate-x2 and
   decimate-x2 overlap-save identities (44.1 -> 16 k, the ÷2-last cascade, is
   already in [mains] and Q3/Q6). Same signals, same ruler, same Q1/Q2
   thresholds as everywhere — the executor is not allowed to move a quality
   number the filters do not. Both surfaces, both dtypes. *)

let q_ols_classes () =
  test "Q1/Q2 hold on the x2/÷2 OLS classes at `High" (fun () ->
      List.iter
        (fun (sr, target) ->
          let c = cfg (sr, target) in
          List.iter
            (fun s ->
              List.iter
                (fun p ->
                  let sfdr_min = match p with F64 -> 130. | F32 -> 125. in
                  List.iter
                    (fun f ->
                      let y = convert s p c (tone ~sr ~f ~seconds:2.) in
                      let mags = spectrum y in
                      let d = sfdr mags and t = thdn mags in
                      if d < sfdr_min then
                        failf "%d->%d %s %s %g Hz: SFDR %.1f dB < %.0f" sr
                          target s.sname (pname p) f d sfdr_min ;
                      if t > -125. then
                        failf "%d->%d %s %s %g Hz: THD+N %.1f dB > -125" sr
                          target s.sname (pname p) f t )
                    (* both directions share the 4 kHz lower Nyquist; the tones
                       sit inside its 3652 Hz passband edge *)
                    [400.; 1000.; 3000.] )
                precs )
            surfaces )
        [(8000, 48000); (48000, 8000)] )

(* {2 Q9 — round trip} *)

let q9 () =
  test "Q9: 44.1 -> 48 -> 44.1 round-trip SNR" (fun () ->
      let rng = Random.State.make [|0x51ab|] in
      let sr = 44100 in
      let n = sr in
      let freqs =
        List.init 20 (fun _ -> 100. +. Random.State.float rng 18000.)
      in
      let phases =
        List.map (fun _ -> Random.State.float rng (2. *. pi)) freqs
      in
      let x =
        Array.init n (fun i ->
            let t = Float.of_int i /. Float.of_int sr in
            List.fold_left2
              (fun acc f ph ->
                acc +. (0.05 *. Float.sin ((2. *. pi *. f *. t) +. ph)) )
              0. freqs phases )
      in
      let up = cfg (44100, 48000) and down = cfg (48000, 44100) in
      List.iter
        (fun s ->
          List.iter
            (fun p ->
              let limit = match p with F64 -> 110. | F32 -> 100. in
              let mid = convert s p up x in
              let y = convert s p down mid in
              if Array.length y <> n then
                failf "%s %s: round trip length %d <> %d" s.sname (pname p)
                  (Array.length y) n ;
              let i0 = n / 10 in
              let sig_p = ref 0. and err_p = ref 0. in
              for i = i0 to n - i0 - 1 do
                sig_p := !sig_p +. (x.(i) *. x.(i)) ;
                let e = x.(i) -. y.(i) in
                err_p := !err_p +. (e *. e)
              done ;
              let snr = 10. *. Float.log10 (!sig_p /. !err_p) in
              if snr < limit then
                failf "%s %s: round-trip SNR %.1f dB < %.0f" s.sname (pname p)
                  snr limit )
            precs )
        surfaces )

(* {2 Q10 — the standard-rate matrix} *)

let standard_rates =
  [8000; 11025; 16000; 22050; 24000; 32000; 44100; 48000; 88200; 96000; 192000]

let ulp64 = Float.ldexp 1. (-52)

let q10 () =
  test "Q10: Q1-Q4 hold over all 110 standard-rate pairs" (fun () ->
      List.iter
        (fun sr ->
          List.iter
            (fun target ->
              if sr <> target then begin
                let c = cfg (sr, target) in
                let l = (Resample.Config.rate c).Pipeline.Rate.num in
                let k = Resample.Config.latency c in
                (* memory guard at the documented creation budget (8 MB). The
                   quantity is the single-stage bank formula over the composite
                   L and K — exact for single-stage plans, an upper proxy for
                   cascades (their composite K folds both stage delays over one
                   L while the real footprint is two far smaller banks, enforced
                   per stage at create; worst standard-rate proxy: 11025 ->
                   192000 at 4.3 MB). *)
                let bank_bytes = l * ((2 * k) + 1) * 8 in
                if bank_bytes > 8 * 1024 * 1024 then
                  failf "%d->%d: bank %d bytes > 8 MB" sr target bank_bytes ;
                let nyq = Float.of_int (Stdlib.min sr target) /. 2. in
                (* Q1/Q2 at scaled tone positions (the 1/5/10/17 kHz set as
                   fractions of the lower Nyquist) *)
                List.iter
                  (fun frac ->
                    let f = frac *. nyq in
                    let y = convert c_path F64 c (tone ~sr ~f ~seconds:1.) in
                    let mags = spectrum y in
                    let d = sfdr mags and t = thdn mags in
                    if d < 130. then
                      failf "%d->%d %g Hz: SFDR %.1f dB < 130" sr target f d ;
                    if t > -125. then
                      failf "%d->%d %g Hz: THD+N %.1f dB > -125" sr target f t )
                  [0.045; 0.23; 0.45; 0.79] ;
                (* Q4 flatness *)
                List.iter
                  (fun frac ->
                    let f = frac *. nyq in
                    let y = convert c_path F64 c (tone ~sr ~f ~seconds:1.) in
                    let dev =
                      Float.abs (20. *. Float.log10 (amp_at ~sr:target ~f y))
                    in
                    if dev > 0.01 then
                      failf "%d->%d %g Hz: gain off by %.4f dB > 0.01" sr target
                        f dev )
                  [0.02; 0.5; 0.913] ;
                (* the GEMM surface stays bound to the executor here too *)
                let f = 0.23 *. nyq in
                let x = tone ~sr ~f ~seconds:1. in
                let a = convert c_path F64 c x in
                let b = convert (List.nth surfaces 1) F64 c x in
                let peak =
                  Array.fold_left (fun m v -> Float.max m (Float.abs v)) 0. a
                in
                let worst = ref 0. in
                Array.iteri
                  (fun i v ->
                    let d = Float.abs (v -. b.(i)) in
                    if d > !worst then worst := d )
                  a ;
                (* The divergence grows with the reduced filter's length:
                   measured worst across the matrix is 26 ULP of peak at 192000
                   -> 24000 (1515 taps; about -290 dBFS). Gate at the next power
                   of two. *)
                if !worst > 32. *. peak *. ulp64 then
                  failf "%d->%d: GEMM diverges by %.1f ULP of peak" sr target
                    (!worst /. (peak *. ulp64))
              end )
            standard_rates )
        standard_rates )

let suite =
  [ group "quality"
      [ q1_q2 ()
      ; q1_tiers ()
      ; q3 ()
      ; q4 ()
      ; q5 ()
      ; q6 ()
      ; q6_tiers ()
      ; q_ols_classes ()
      ; q9 ()
      ; q10 () ] ]
