(* librosa golden vectors for [Convert.power_to_db] and
   [Convert.amplitude_to_db], generated by [test/generate_vectors.py] (the [db]
   suite) against the pinned librosa. The cases cover fixed references, the
   [amin] clamp (values below the floor), [top_db] clamping (including a
   rank-two input whose threshold is global across rows), the sign conventions
   on negative entries, and both element dtypes. Each case carries its input in
   the params, flattened in C order and exactly representable in the case
   dtype. *)

open Windtrap
open Soundml

let vectors_dir = Filename.concat ".." (Filename.concat "vectors" "db")

let golden_files = Tutils.Golden.load_dir vectors_dir

let input_values (case : Tutils.Golden.case) =
  Tutils.Golden.param case "input"
  |> Yojson.Safe.Util.to_list
  |> List.map Yojson.Safe.Util.to_number
  |> Array.of_list

let top_db (case : Tutils.Golden.case) =
  match Tutils.Golden.param case "top_db" with
  | `Null ->
      None
  | json ->
      Some (Yojson.Safe.Util.to_number json)

let convert_of_case (case : Tutils.Golden.case) =
  match Tutils.Golden.string_param case "function" with
  | "power_to_db" ->
      Convert.power_to_db
  | "amplitude_to_db" ->
      Convert.amplitude_to_db
  | other ->
      failf "golden case %s: unknown function %s" case.name other

let run_case dtype ~rtol ~atol (case : Tutils.Golden.case) =
  let convert = convert_of_case case in
  let reference = Tutils.Golden.float_param case "reference" in
  let amin = Tutils.Golden.float_param case "amin" in
  let input = Nx.create dtype case.shape (input_values case) in
  let actual = convert ~reference ~amin ?top_db:(top_db case) input in
  Tutils.check_close ~rtol ~atol ~shape:case.shape ~msg:case.name
    ~expected:case.values actual

let case_test (case : Tutils.Golden.case) =
  test case.name (fun () ->
      (* librosa computes in the input dtype: float32 goldens carry float32
         results, compared against our float32 path within float32-log
         tolerances *)
      match Tutils.Golden.string_param case "dtype" with
      | "float32" ->
          run_case Nx.float32 ~rtol:1e-4 ~atol:1e-4 case
      | "float64" ->
          run_case Nx.float64 ~rtol:1e-10 ~atol:1e-10 case
      | other ->
          failf "golden case %s: unknown dtype %s" case.name other )

let all_cases =
  List.concat_map (fun (file : Tutils.Golden.file) -> file.cases) golden_files

let suite =
  [ group "librosa-golden"
      ( test "the vectors are present" (fun () ->
            is_true ~msg:"one case per function, parameter set and dtype"
              (List.length all_cases >= 18) )
      :: List.map case_test all_cases ) ]
