# Inspired by https://github.com/savonet/build-and-test-ocaml-module/blob/main/action.yml
# Thanks for the savonet team for building such an amazing software :p
name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macos-latest, windows-latest]
        ocaml-compiler:
          - "5.3.0"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml ${{ matrix.ocaml-compiler }} on ${{ matrix.os }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Install libsoxr-dev
        run: |
            sudo apt-get update
            sudo apt-get install -y libsoxr-dev
        shell: bash

      - name: Install libsndfile and libsamplerate
        run: |
            sudo apt-get install libsndfile-dev libsamplerate0-dev

      - name: Install llvm # required for rune
        run: |
            sudo apt-get install libllvm-20-ocaml-dev libllvm20 llvm-20 llvm-20-dev llvm-20-doc llvm-20-examples llvm-20-runtime

      - name: Lock the dependencies 
        run: opam exec -- dune pkg lock
        shell: bash

      - name: Build SoundML
        run: opam exec -- dune build
        shell: bash
