# Inspired by https://github.com/savonet/build-and-test-ocaml-module/blob/main/action.yml
# Thanks for the savonet team for building such an amazing software :p

name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macos-latest, windows-latest]
        ocaml-compiler:
          - "5.3.0" # Latest stable
          - "5.2.0"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml ${{ matrix.ocaml-compiler }} on ${{ matrix.os }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      # temporary, waiting for the conf-soxr package to be published to opam repo
      - name: Install libsoxr-dev
        run: |
            sudo apt-get update
            sudo apt-get install -y libsoxr-dev
        shell: bash

      - name: Install SoundML dependencies (with test)
        run: opam install . --deps-only --with-test --yes --confirm-level=unsafe-yes --verbose
        shell: bash

      - name: Run tests
        run: opam exec -- dune runtest
        shell: bash