# Some of the CI has been inspired from https://github.com/savonet/build-and-test-ocaml-module/blob/main/action.yml
# Thanks for the savonet team for building such an amazing software :p

name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler:
          - "5.2"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install SoundML package
        run: |
          opam --cli=2.3 install --verbose --confirm-level=unsafe-yes --with-test .
        shell: bash

      - name: Run tests
        run: opam exec -- dune runtest

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.2"
          dune-cache: true

      - uses: ocaml/setup-ocaml/lint-fmt@v2
